#pragma once


enum enumFloorSprites{
	SPRITEFLOOR_NA = 0,
	SPRITEFLOOR_DETAILED = 1,
	SPRITEFLOOR_GRASS = 2,
	SPRITEFLOOR_STONE = 3,
	SPRITEFLOOR_DIRT = 4,
	SPRITEFLOOR_PEBBLES = 5,
	SPRITEFLOOR_BOULDER = 6,
	SPRITEFLOOR_VEGETATION = 7,
	SPRITEFLOOR_PLOWED = 8,
	SPRITEFLOOR_DRYGRASS = 9,
	SPRITEFLOOR_WOOD = 10,
};


enum enumObjectSprites{
	SPRITEOBJECT_NA = 0,
	SPRITEOBJECT_STAIRDOWN = 1,
	SPRITEOBJECT_STAIRUP = 2,
	SPRITEOBJECT_TREE_BROADLEAF = 3,
  SPRITEOBJECT_TREE_BROADLEAF2 = 4,
  SPRITEOBJECT_TREE_CONIFER = 5,
  SPRITEOBJECT_CACTUS = 6,
	SPRITEOBJECT_SHRUB = 7,

	SPRITEOBJECT_WATERLEVEL1 = 8,
	SPRITEOBJECT_WATERLEVEL2 = 9,
	SPRITEOBJECT_WATERLEVEL3 = 10,
	SPRITEOBJECT_WATERLEVEL4 = 11,
	SPRITEOBJECT_WATERLEVEL5 = 12,
	SPRITEOBJECT_WATERLEVEL6 = 13,
	SPRITEOBJECT_WATERLEVEL7 = 14,
	SPRITEOBJECT_FARM = 15,


	SPRITEOBJECT_DOORROCK = 16,
	SPRITEOBJECT_DOORWOOD = 17,
  SPRITEOBJECT_DOORWOOD_WILLOW = 18,
  SPRITEOBJECT_DOORROCK_MIR = 19,
	SPRITEOBJECT_DOORWOOD_MIR = 20,
  SPRITEOBJECT_DOORWOOD_WILLOW_MIR = 21,

  SPRITEOBJECT_ARMORSTAND = 24,
  SPRITEOBJECT_BEDWOOD = 25,
  SPRITEOBJECT_TABLE_WOOD = 26,
  SPRITEOBJECT_TABLE_ROCK = 27,
  SPRITEOBJECT_CHAIR_WOOD = 28,
  SPRITEOBJECT_CHAIR_ROCK = 29,
  SPRITEOBJECT_STATUE = 30,
  SPRITEOBJECT_CABINET = 31,

	SPRITEOBJECT_WATERLEVEL1_LAVA = 32,
	SPRITEOBJECT_WATERLEVEL2_LAVA = 33,
	SPRITEOBJECT_WATERLEVEL3_LAVA = 34,
	SPRITEOBJECT_WATERLEVEL4_LAVA = 35,
	SPRITEOBJECT_WATERLEVEL5_LAVA = 36,
	SPRITEOBJECT_WATERLEVEL6_LAVA = 37,
	SPRITEOBJECT_WATERLEVEL7_LAVA = 38,

	SPRITEOBJECT_PAVEDFLOOR = 40,
	SPRITEOBJECT_COLUMN = 41,
  SPRITEOBJECT_STAIRDOWN_WOOD = 44,
  SPRITEOBJECT_STAIRUP_WOOD = 45,
  SPRITEOBJECT_STAIRUP_MIR = 46,
  SPRITEOBJECT_STAIRUP_WOOD_MIR = 47,

  SPRITEOBJECT_CURSORZONE = 48,
  SPRITEOBJECT_BLUEPRINT = 49,
  SPRITEOBJECT_STOCKPILE = 50,


  SPRITEOBJECT_WALL_NA = 64,
  SPRITEOBJECT_WALL_STONE_ROUGH = 65,
  SPRITEOBJECT_WALL_MINSTONE_ROUGH = 66,
  SPRITEOBJECT_WALL_LAVASTONE_ROUGH = 67,
  SPRITEOBJECT_WALL_FEATSTONE_ROUGH = 68,
  SPRITEOBJECT_WALL_SOIL = 69,
	SPRITEOBJECT_WALL_STONE_SMOOTH = 70,
  
  //SPRITEOBJECT_WALL_CONSTR_SMOOTH = 73,
  SPRITEOBJECT_WALL_CONSTR = 73,
  SPRITEOBJECT_WALL_PILLAR = 74,
  SPRITEOBJECT_WALL_FORTIFICATION = 75,

	SPRITEOBJECT_WALL_WOOD = 77,
  SPRITEOBJECT_WALL_WOOD_FORTIFICATION = 78,
  
	

  SPRITEOBJECT_BRIDGE_C = 80,
  SPRITEOBJECT_BRIDGE_C2 = 81,
  SPRITEOBJECT_BRIDGE_S = 82,
  SPRITEOBJECT_BRIDGE_N = 83,
  SPRITEOBJECT_BRIDGE_W = 84,
  SPRITEOBJECT_BRIDGE_E = 85,
  SPRITEOBJECT_BRIDGE_SW = 86,
  SPRITEOBJECT_BRIDGE_NE = 87,
  SPRITEOBJECT_BRIDGE_SE = 88,
  SPRITEOBJECT_BRIDGE_NW = 89,
};

enum enumRampMaterials{
  SPRITERAMP_GENERIC = 0,
  SPRITERAMP_GRASS = 1,
};

enum BlockIDs{

  ID_STONE_FORTIFICATION = 65,
  ID_STONE_WALL_RD2 = 307,
  ID_CNSTFLOOR = 493,
	ID_CNSTFORTIFICATION = 494,

  ID_CNSTR_STAIR_UPDOWN = 515,
  ID_CNSTR_STAIR_DOWN = 516,
  ID_CNSTR_STAIR_UP = 517,

	//new ones
	ID_WOODFLOOR = 900,
	ID_WOODFLOOR_DETAIL = 901,
	ID_WOODFLOOR_STAIR_UPDOWN = 905,
  ID_WOODFLOOR_STAIR_DOWN = 906,
  ID_WOODFLOOR_STAIR_UP = 907,
  
	ID_WOODFORTIFICATION = 910,
	ID_WOODWALL = 911,
	ID_WOODPILLAR = 912,
	

	       // case 307: //stone wall rd2
        //case 308: //stone wall r2d
        //case 309: //stone wall r2u
        //case 310: //stone wall ru2
        //case 311: //stone wall l2u
        //case 312: //stone wall lu2
        //case 313: //stone wall l2d
        //case 314: //stone wall ld2
        //case 315: //stone wall lrud
        //case 316: //stone wall rud
        //case 317: //stone wall lrd
        //case 318: //stone wall lru
        //case 319: //stone wall lud
        //case 320: //stone wall rd
        //case 321: //stone wall ru
        //case 322: //stone wall lu
        //case 323: //stone wall ld
        //case 324: //stone wall ud
        //case 325: //stone wall lr
};


int GetWallSpriteMap(int in);
int GetFloorSpriteMap(int in);
int GetUpStairTypeMap(int in, bool mirrored);
int GetDownStairTypeMap(int in);
int GetRampMaterialTypeMap(int in);
int GetWallSpriteVegitation( int type, int index , int x, int y);

