/* #undef ALLEGRO_CFG_KCM_ALSA */
/* #undef ALLEGRO_CFG_KCM_OPENAL */
#define ALLEGRO_CFG_KCM_DSOUND
/* #undef ALLEGRO_CFG_KCM_OSS */
/* #undef ALLEGRO_CFG_KCM_PULSEAUDIO */
/* #undef ALLEGRO_CFG_KCM_AQUEUE */
